server:
  port: 8080

spring:
  application:
    name: AssessMe
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    root: info

db:
  host: db-5308.cs.dal.ca
  port: 3306
  database: CSCI5308_13_PRODUCTION
  username: CSCI5308_13_PRODUCTION_USER
  password: CSCI5308_13_PRODUCTION_13807